### ISSUE TITLE
Derivatives are incorrect in multipoint groups with multiple aerostructural scenarios

### ISSUE THREAD

**Issue by A-CGray** [OpenMDAO/mphys#145] opened 2023-05-01 02:12 UTC
## Summary of the issue

In a `Multipoint` group with 2 aerostructural scenarios, a and b, the totals from scenario a are incorrect while the totals from scenario b are correct. If the conditions (flight conditions, structural loading) of scenario b are changed to match those of scenario a, then the derivatives of both scenarios are correct. This suggests that some scenario specific state data from scenario b is mistakenly being used when computing the totals of scenario a.

## Recreating the issue

The output below was all produced running in serial on the MDOLab's [u22-gcc-ompi-latest docker container](https://hub.docker.com/layers/mdolab/public/u22-gcc-ompi-latest/images/sha256-5b241709bd970dbd36cbf215f4f2afacdf1e1e5b14f8ffa9d7345eb1a8acf170?context=explore) with the following packages

```
ubuntu 22.04
gcc 11.3.0
python 3.9.6
openmpi-4.1.4
petsc-3.18.3

Package                       Version   
----------------------------- --------- 
adflow                        2.8.0
Cython                        0.29.34
funtofem                      0.2
numpy                         1.21.5
numpy-stl                     3.0.1
openmdao                      3.20.0
scipy                         1.7.3
tacs                          3.2.0    
```

The problem can be reproduced by running the `mphys_as_2scenario.py` script in the `examples/aerostructural/mach_tutorial_wing/adflow_meld_tacs` directory of this repo. I will attach a patch file below which adds a call to `check_totals` to the script and makes the `maneuver` scenario's aeroProblem more different from the `cruise` aeroProblem to make the issue more clear.

```python
aoa0 = 2.0
ap0 = AeroProblem(
    name="cruise",
    mach=0.85,
    altitude=10000,
    alpha=aoa0,
    areaRef=45.5,
    chordRef=3.25,
    evalFuncs=["lift", "drag", "cl", "cd"],
)
ap0.addDV("alpha", value=aoa0, name="aoa", units="deg")

aoa1 = 5.0
ap1 = AeroProblem(
    name="maneuver",
    mach=0.5,
    altitude=0,
    alpha=aoa1,
    areaRef=45.5,
    chordRef=3.25,
    evalFuncs=["lift", "drag", "cl", "cd"],
)
ap1.addDV("alpha", value=aoa1, name="aoa", units="deg")
```

Then, running `python mphys_as_2scenario.py` produces:
```
-----------------
Total Derivatives
-----------------

'<output>'                     wrt '<variable>'                   | calc mag.  | check mag. | a(cal-chk) | r(cal-chk)
---------------------------------------------------------------------------------------------------------------------

'cruise.aero_post.cd'          wrt 'aoa0'                         | 6.9906e-04 | 1.6990e-03 | 9.9994e-04 | 5.8855e-01 >ABS_TOL >REL_TOL
'cruise.aero_post.cd'          wrt 'aoa1'                         | 0.0000e+00 | 2.6275e-06 | 2.6275e-06 | 1.0000e+00 >ABS_TOL >REL_TOL
'maneuver.aero_post.cd'        wrt 'aoa0'                         | 0.0000e+00 | 9.3675e-08 | 9.3675e-08 | 1.0000e+00 >REL_TOL
'maneuver.aero_post.cd'        wrt 'aoa1'                         | 3.1859e-03 | 3.1860e-03 | 9.7114e-08 | 3.0481e-05 >REL_TOL
```

After updating to latest versions of some packages:
tacs-3.2.1
mphys-1.1.0 
openmdao-3.26.0
funtofem master branch @2ff3f1c639ce2ce146cc3db670abe3f90155c906
adflow main branch @b97914be9db29ab6c8f362099618d4de9df39b54

The result is the same:

```
-----------------
Total Derivatives
-----------------

'<output>'                     wrt '<variable>'                   | calc mag.  | check mag. | a(cal-chk) | r(cal-chk)
---------------------------------------------------------------------------------------------------------------------

'cruise.aero_post.cd'          wrt 'aoa0'                         | 6.9906e-04 | 1.6990e-03 | 9.9994e-04 | 5.8855e-01 >ABS_TOL >REL_TOL
'cruise.aero_post.cd'          wrt 'aoa1'                         | 0.0000e+00 | 2.6275e-06 | 2.6275e-06 | 1.0000e+00 >ABS_TOL >REL_TOL
'maneuver.aero_post.cd'        wrt 'aoa0'                         | 0.0000e+00 | 9.3675e-08 | 9.3675e-08 | 1.0000e+00 >REL_TOL
'maneuver.aero_post.cd'        wrt 'aoa1'                         | 3.1859e-03 | 3.1860e-03 | 9.7114e-08 | 3.0481e-05 >REL_TOL
```

Then, if I make `ap1` identical to `ap0`, the derivatives for `ap0` are fixed:

```python
aoa0 = 2.0
        ap0 = AeroProblem(
    name="cruise",
    mach=0.85,
    altitude=10000,
    alpha=aoa0,
    areaRef=45.5,
    chordRef=3.25,
    evalFuncs=["lift", "drag", "cl", "cd"],
)
ap0.addDV("alpha", value=aoa0, name="aoa", units="deg")

aoa1 = 2.0
ap1 = AeroProblem(
    name="cruise",
    mach=0.85,
    altitude=10000,
    alpha=aoa0,
    areaRef=45.5,
    chordRef=3.25,
    evalFuncs=["lift", "drag", "cl", "cd"],
)
ap1.addDV("alpha", value=aoa1, name="aoa", units="deg")
```

```
-----------------
Total Derivatives
-----------------

'<output>'                     wrt '<variable>'                   | calc mag.  | check mag. | a(cal-chk) | r(cal-chk)
---------------------------------------------------------------------------------------------------------------------

'cruise.aero_post.cd'          wrt 'aoa0'                         | 1.6968e-03 | 1.6990e-03 | 2.2253e-06 | 1.3098e-03 >ABS_TOL >REL_TOL
'cruise.aero_post.cd'          wrt 'aoa1'                         | 0.0000e+00 | 2.6275e-06 | 2.6275e-06 | 1.0000e+00 >ABS_TOL >REL_TOL
'maneuver.aero_post.cd'        wrt 'aoa0'                         | 0.0000e+00 | 2.6358e-06 | 2.6358e-06 | 1.0000e+00 >ABS_TOL >REL_TOL
'maneuver.aero_post.cd'        wrt 'aoa1'                         | 1.6966e-03 | 1.6992e-03 | 2.6407e-06 | 1.5541e-03 >ABS_TOL >REL_TOL
```

The same thing happens if `ap0` is made identical to `ap1` suggesting that this is not an issue with any specific analysis condition but instead with data from the second scenario being mistakenly used by the first.

Although here I am modifying the aeroProblems to demonstrate the issue, I don't believe the issue is specific to ADflow, since the 2 pt aero-only example in `examples/aero_only/mach_tutorial_wing/adflow/mphys_aero_opt_2pt.py` produces accurate derivatives for both scenarios.

**Comment by A-CGray** [comment] 2023-05-01 02:14
Patch for the aerostructural example to produce the above results

```patch
--- mphys_as_2scenario.py	2023-04-30 21:15:04.388398203 -0400
+++ mphys_as_2scenario-New.py	2023-04-30 21:40:56.424473571 -0400
@@ -17,7 +17,7 @@
 
 parser = argparse.ArgumentParser()
 parser.add_argument("--xfer", default="meld", choices=["meld", "rlt"])
-parser.add_argument("--level", type=str, default="L1")
+parser.add_argument("--level", type=str, default="L3")
 args = parser.parse_args()
 
 if args.xfer == "meld":
@@ -147,8 +147,8 @@
         aoa1 = 5.0
         ap1 = AeroProblem(
             name="maneuver",
-            mach=0.85,
-            altitude=10000,
+            mach=0.5,
+            altitude=0,
             alpha=aoa1,
             areaRef=45.5,
             chordRef=3.25,
@@ -181,17 +181,18 @@
 prob = om.Problem()
 prob.model = Top()
 model = prob.model
-prob.setup()
+prob.setup(mode="rev")
 om.n2(prob, show_browser=False, outfile="mphys_as_adflow_tacs_%s_2pt.html" % args.xfer)
 prob.run_model()
+prob.check_totals(of=["cruise.aero_post.cd","maneuver.aero_post.cd"], wrt=["aoa0", "aoa1"], compact_print=True, step=1e-5)
 
-prob.model.list_outputs()
+# prob.model.list_outputs()
 
-if prob.model.comm.rank == 0:
-    print("Cruise")
-    print("cl =", prob["cruise.aero_post.cl"])
-    print("cd =", prob["cruise.aero_post.cd"])
-
-    print("Maneuver")
-    print("cl =", prob["maneuver.aero_post.cl"])
-    print("cd =", prob["maneuver.aero_post.cd"])
+# if prob.model.comm.rank == 0:
+#     print("Cruise")
+#     print("cl =", prob["cruise.aero_post.cl"])
+#     print("cd =", prob["cruise.aero_post.cd"])
+
+#     print("Maneuver")
+#     print("cl =", prob["maneuver.aero_post.cl"])
+#     print("cd =", prob["maneuver.aero_post.cd"]) 
```

**Comment by kejacobson** [comment] 2023-05-01 13:21
@A-CGray , can you try a newer version of OpenMDAO? We found some parallel bugs related to different conventions for when to do an allreduce(). TACS and OpenMDAO were doing it one way, but most of the other codes including ADflow were doing it a different way. This resulted in [POEM 75](https://github.com/OpenMDAO/POEMs/blob/master/POEM_075.md). This convention change is TACS 3.2.1, but you'll need OM 3.25 or later.

**Comment by A-CGray** [comment] 2023-05-01 14:02
> @A-CGray , can you try a newer version of OpenMDAO? We found some parallel bugs related to different conventions for when to do an allreduce(). TACS and OpenMDAO were doing it one way, but most of the other codes including ADflow were doing it a different way. This resulted in [POEM 75](https://github.com/OpenMDAO/POEMs/blob/master/POEM_075.md). This convention change is TACS 3.2.1, but you'll need OM 3.25 or later.

Sorry I missed openmdao from the list of updated packages for the second set of results. This issue showed up in both OM 3.20 and 3.26. Also, all the results here are run in serial so this is not a parallelism issue

**Comment by A-CGray** [comment] 2023-05-01 20:07
Did some more digging experimenting with using a single builder or separate builders for each scenario, results below are run with the following package versions:

```
Package                       Version
----------------------------- -----------
adflow                        2.8.0
funtofem                      0.2
mphys                         Current main branch
openmdao                      3.26.1.dev0 (current main branch)
tacs                          3.2.1
```

And the following calls to `check_totals`

```python
prob.check_totals(
      of=[
          "cruise.aero_post.cd",
          "maneuver.aero_post.cd",
          "cruise.ks_vmfailure",
          "maneuver.ks_vmfailure",
      ],
      wrt=["aoa0", "aoa1"],
      method="fd",
      step=1e-4,
      compact_print=True,
      out_stream=f,
      abs_err_tol=1e6,
      rel_err_tol=1e-2,
  )
  prob.check_totals(
      of=[
          "cruise.aero_post.cd",
          "maneuver.aero_post.cd",
          "cruise.ks_vmfailure",
          "maneuver.ks_vmfailure",
      ],
      wrt=["dv_struct"],
      method="fd",
      step=1e-4,
      compact_print=True,
      directional=True,
      out_stream=f,
      abs_err_tol=1e6,
      rel_err_tol=1e-2,
  )
  ```

## Using the same builders for both cruise and maneuver scenarios

```text
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>' |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+==================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | 'aoa0'           |  6.9902e-04 |  1.6967e-03 |  9.9766e-04 |  5.8801e-01 |  >REL_TOL  |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | 'aoa0'           |  1.1390e-01 |  1.1045e-01 |  3.4507e-03 |  3.1243e-02 |  >REL_TOL  |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | 'aoa1'           |  3.1859e-03 |  3.1859e-03 |  3.9210e-08 |  1.2307e-05 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | 'aoa1'           |  1.1160e-01 |  1.1160e-01 |  8.1252e-07 |  7.2807e-06 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+

+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>'  |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+===================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | (d)('dv_struct',) |  1.8737e-04 |  7.9080e-04 |  9.7817e-04 |  1.2369e+00 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | (d)('dv_struct',) |  1.3503e-01 |  1.5675e-01 |  2.1719e-02 |  1.3856e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | (d)('dv_struct',) |  2.5000e-02 |  2.7090e-02 |  2.0903e-03 |  7.7162e-02 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | (d)('dv_struct',) |  1.5108e+01 |  1.7509e+01 |  2.4013e+00 |  1.3714e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
```

## Using separate ADflow, TACS and MELD builders for each scenario

```
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>' |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+==================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | 'aoa0'           |  1.6964e-03 |  1.6967e-03 |  3.1186e-07 |  1.8381e-04 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | 'aoa0'           |  1.1040e-01 |  1.1045e-01 |  4.2086e-05 |  3.8105e-04 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | 'aoa1'           |  3.1859e-03 |  3.1859e-03 |  3.9173e-08 |  1.2296e-05 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | 'aoa1'           |  1.1160e-01 |  1.1160e-01 |  8.1325e-07 |  7.2873e-06 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+

+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>'  |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+===================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | (d)('dv_struct',) |  7.1770e-04 |  7.9080e-04 |  7.3100e-05 |  9.2438e-02 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | (d)('dv_struct',) |  1.3593e-01 |  1.5675e-01 |  2.0816e-02 |  1.3280e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | (d)('dv_struct',) |  2.5000e-02 |  2.7090e-02 |  2.0900e-03 |  7.7151e-02 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | (d)('dv_struct',) |  1.5108e+01 |  1.7509e+01 |  2.4013e+00 |  1.3714e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
```

## Using a single ADflow builder and separate TACS and MELD builders

```
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>' |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+==================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | 'aoa0'           |  6.9902e-04 |  1.6967e-03 |  9.9766e-04 |  5.8801e-01 |  >REL_TOL  |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | 'aoa0'           |  1.1390e-01 |  1.1045e-01 |  3.4507e-03 |  3.1243e-02 |  >REL_TOL  |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | 'aoa1'           |  3.1859e-03 |  3.1859e-03 |  3.9210e-08 |  1.2307e-05 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | 'aoa1'           |  1.1160e-01 |  1.1160e-01 |  8.1252e-07 |  7.2807e-06 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+

+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>'  |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+===================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | (d)('dv_struct',) |  1.8737e-04 |  7.9080e-04 |  9.7817e-04 |  1.2369e+00 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | (d)('dv_struct',) |  1.3503e-01 |  1.5675e-01 |  2.1719e-02 |  1.3856e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | (d)('dv_struct',) |  2.5000e-02 |  2.7090e-02 |  2.0903e-03 |  7.7162e-02 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | (d)('dv_struct',) |  1.5108e+01 |  1.7509e+01 |  2.4013e+00 |  1.3714e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
```

## Using a single TACS builder and separate ADflow and MELD builders

```
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>' |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+==================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | 'aoa0'           |  1.6964e-03 |  1.6967e-03 |  3.1186e-07 |  1.8381e-04 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | 'aoa0'           |  1.1040e-01 |  1.1045e-01 |  4.2086e-05 |  3.8105e-04 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | 'aoa1'           |  3.1859e-03 |  3.1859e-03 |  3.9173e-08 |  1.2296e-05 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | 'aoa1'           |  1.1160e-01 |  1.1160e-01 |  8.1325e-07 |  7.2873e-06 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+

+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>'  |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+===================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | (d)('dv_struct',) |  7.1770e-04 |  7.9080e-04 |  7.3100e-05 |  9.2438e-02 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | (d)('dv_struct',) |  1.3593e-01 |  1.5675e-01 |  2.0816e-02 |  1.3280e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | (d)('dv_struct',) |  2.5000e-02 |  2.7090e-02 |  2.0900e-03 |  7.7151e-02 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | (d)('dv_struct',) |  1.5108e+01 |  1.7509e+01 |  2.4013e+00 |  1.3714e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
```

**Comment by kejacobson** [comment] 2023-05-01 20:19
Thanks for the update. So this would suggest that the issue is not related to TACS. I think MELD is also ok because we get good derivatives with MELD using other aero codes. If you want be sure about MELD, you can use the same MELD and TACS but separate ADflow. The MELD builder constructor requires an aero_builder, but that's just for sizing its vectors, so it should be ok to give the MELD constructor just one of the ADflow builders then use the meld builder for both scenarios.

**Comment by A-CGray** [comment] 2023-05-01 20:22
> The MELD builder constructor requires an aero_builder, but that's just for sizing its vectors, so it should be ok to give the MELD constructor just one of the ADflow builders then use the meld builder for both scenarios.

Ah, that's good to know, I hadn't tried that combo yet because I saw the MELD builder needed that aero and structu builders as inputs. Will give it a go now

**Comment by A-CGray** [comment] 2023-05-01 20:31
## Using a single TACS and MELD builder, separate ADflow builders

```
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>' |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+==================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | 'aoa0'           |  1.6964e-03 |  1.6967e-03 |  3.1186e-07 |  1.8381e-04 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | 'aoa0'           |  1.1040e-01 |  1.1045e-01 |  4.2086e-05 |  3.8105e-04 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | 'aoa1'           |  3.1859e-03 |  3.1859e-03 |  3.9173e-08 |  1.2296e-05 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | 'aoa1'           |  1.1160e-01 |  1.1160e-01 |  8.1325e-07 |  7.2873e-06 |            |
+-------------------------+------------------+-------------+-------------+-------------+-------------+------------+

+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| of '<variable>'         | wrt '<variable>'  |   calc mag. |  check mag. |  a(cal-chk) |  r(cal-chk) | error desc |
+=========================+===================+=============+=============+=============+=============+============+
| 'cruise.aero_post.cd'   | (d)('dv_struct',) |  7.1770e-04 |  7.9080e-04 |  7.3100e-05 |  9.2438e-02 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'cruise.ks_vmfailure'   | (d)('dv_struct',) |  1.3593e-01 |  1.5675e-01 |  2.0816e-02 |  1.3280e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.aero_post.cd' | (d)('dv_struct',) |  2.5000e-02 |  2.7090e-02 |  2.0900e-03 |  7.7151e-02 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
| 'maneuver.ks_vmfailure' | (d)('dv_struct',) |  1.5108e+01 |  1.7509e+01 |  2.4013e+00 |  1.3714e-01 |  >REL_TOL  |
+-------------------------+-------------------+-------------+-------------+-------------+-------------+------------+
```

**Comment by kejacobson** [comment] 2023-05-02 00:19
Ok. That points to something in ADflow. @anilyil will need to help from here.

**Comment by A-CGray** [comment] 2023-05-02 00:24
Yeah I discussed with @anilyil , for now I will get by with the multiple builder workaround and after the Aviation rush we will take a look into this together

**Comment by kejacobson** [comment] 2023-05-02 00:29
Sounds good. If you can force qinf = 0, and check the same functions you should be able to isolate the effect of the mesh deformation by breaking the coupling loop. That is, if all your derivatives match with qinf=0, then it is probably meshdef.

**Comment by kejacobson** [comment] 2023-05-02 01:47
I guess you could get the same effect by setting the linear and nonlinear solvers to RunOnce solvers

**Comment by kejacobson** [comment] 2023-06-09 13:18
@A-CGray, is it ok to close this issue since you've determined that is the UM mesh wrapping?

**Comment by A-CGray** [comment] 2023-06-09 13:34
> @A-CGray, is it ok to close this issue since you've determined that is the UM mesh wrapping?

Yeah sorry, I should've done that a while ago, go ahead

**Closed** 2023-06-09 13:35 UTC
